# Use small Alpine Linux image
FROM node:12-alpine

# Set environment variables
ENV PORT=5000

COPY . app/

WORKDIR /app/

RUN npm install

# Expose port for Node
EXPOSE $PORT

# Start Node server
ENTRYPOINT npm run start